language: node_js
node_js:
- 8
addons:
  ssh_known_hosts: facteus@sshcloud.cluster024.hosting.ovh.net
before_script:
- npm i webpack --save-dev
- npm i @babel/preset-env @babel/preset-react --save-dev
- npm install babel-loader
- npm install --save-dev @babel/core @babel/preset-env
- npm install
script: npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_281d9c9bcab7_key -iv $encrypted_281d9c9bcab7_iv
  -in github_facteus_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/static $TRAVIS_BUILD_DIR/server.js $TRAVIS_BUILD_DIR/compute.js --port 44335 facteus@sshcloud.cluster024.hosting.ovh.net:~/www/
    on:
      branch: master