language: node_js
node_js:
- 12
addons:
  ssh_known_hosts: facteus@sshcloud.cluster024.hosting.ovh.net:44335
before_script:
- cd client
- npm install
- cd ../server
- npm install
script: 
- cd ../client
- npm run build
- cd ../server
- npm run build
