language: node_js
node_js:
- 12
addons:
  ssh_known_hosts: ubuntu@51.210.182.41
before_script:
- cd client
- npm install
- cd ../server
- npm install
script: 
- cd ../client
- npm run build
- cd ..
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- sudo apt-get install jq
- build_nb=`cat $TRAVIS_BUILD_DIR/client/package.json | jq .build.unique | sed 's/"//g'`
- echo "Build number to be deployed:${build_nb}"
- sed -i -e "s/BUILD_NUMBER_PLACEHOLDER/${build_nb}/g" $TRAVIS_BUILD_DIR/client/static/dist/bundle.js
- build_date=`cat $TRAVIS_BUILD_DIR/client/package.json | jq .build.timestamp | sed 's/"//g'`
- echo "Build date to be deployed:${build_date}"
- sed -i -e "s/BUILD_DATE_PLACEHOLDER/${build_date}/g" $TRAVIS_BUILD_DIR/client/static/dist/bundle.js
deploy:
# - provider: script
#   skip_cleanup: true
#   script: rsync -e 'ssh -p 44335' -r --delete-after $TRAVIS_BUILD_DIR/client/static facteus@sshcloud.cluster024.hosting.ovh.net:~/www/ && rsync -e 'ssh -p 44335' -r --delete-after $TRAVIS_BUILD_DIR/server facteus@sshcloud.cluster024.hosting.ovh.net:~/www/
#   on:
#     branch: master
- provider: script
  skip_cleanup: true
  script: rsync -e 'ssh' -r --delete-after $TRAVIS_BUILD_DIR/client/static/* ubuntu@51.210.182.41:/var/www/html/ && rsync -e 'ssh' -r --delete-after $TRAVIS_BUILD_DIR/server/* ubuntu@51.210.182.41:/var/www/server/ &&  rsync -e 'ssh' -r --delete-after $TRAVIS_BUILD_DIR/start-server.sh ubuntu@51.210.182.41:/var/www/  &&  ssh ubuntu@51.210.182.41 chmod u+x /var/www/start-server.sh
  on:
    branch: integration
after_deploy:
- ssh ubuntu@51.210.182.41 /var/www/start-server.sh