language: node_js
node_js:
- 12
addons:
  ssh_known_hosts: facteus@sshcloud.cluster024.hosting.ovh.net:44335
before_script:
- cd client
- npm install
- cd ../server
- npm install
script: 
- cd ../client
- npm run build
- cd ..
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa 
deploy:
# - provider: script
#   skip_cleanup: true
#   script: rsync -e 'ssh -p 44335' -r --delete-after $TRAVIS_BUILD_DIR/client/static facteus@sshcloud.cluster024.hosting.ovh.net:~/www/ && rsync -e 'ssh -p 44335' -r --delete-after $TRAVIS_BUILD_DIR/server facteus@sshcloud.cluster024.hosting.ovh.net:~/www/
#   on:
#     branch: master
- provider: script
  skip_cleanup: true
  script: rsync -e 'ssh' -r --delete-after $TRAVIS_BUILD_DIR/client/static/* ubuntu@51.210.182.41:~/www/html/ && rsync -e 'ssh' -r --delete-after $TRAVIS_BUILD_DIR/server/* ubuntu@51.210.182.41:~/www/server/
  on:
    branch: integration
