language: node_js
node_js:
- 8
addons:
  ssh_known_hosts: facteus@sshcloud.cluster024.hosting.ovh.net
before_script:
- npm i webpack --save-dev
- npm i @babel/preset-env @babel/preset-react --save-dev
- npm install babel-loader
- npm install --save-dev @babel/core @babel/preset-env
- npm install
script: npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -e 'ssh -p 44335' -r --delete-after $TRAVIS_BUILD_DIR/static $TRAVIS_BUILD_DIR/server.js
    $TRAVIS_BUILD_DIR/compute.js facteus@sshcloud.cluster024.hosting.ovh.net:~/www/
  on:
    branch: master
