language: node_js
node_js:
  - 8
before_script:
  - npm i webpack --save-dev
  - npm i @babel/preset-env @babel/preset-react --save-dev
  - npm install babel-loader
  - npm install --save-dev @babel/core @babel/preset-env
  - npm install
script: npm run build