swagger: "2.0"
info:
  description: "This is the facteurs-charge website's API."
  version: "1.0.0"
  title: "Facteurs-charge"
  license:
    name: "GPL-3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.fr.html"
host: "www.facteurs-charge.fr"
basePath: "/api/v1"
tags:
- name: Breakdown
- name: Consumption
- name: Exchange
- name: Zone
schemes:
- "https"

paths:
  /breakdowns:
    get:
      tags:
      - Breakdown
      summary: Retrieve breakdowns
      operationId: getBreakdowns
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/zoneId'
        - $ref: '#/parameters/valueFilter'
        - $ref: '#/parameters/loadFilter'
        - $ref: '#/parameters/powerSourceFilter'
      responses:
        "200":
          description: "All data retreived"
          schema:
            type: array
            items:
              $ref: '#/definitions/breakdown'
        "400":
          description: "Bad parameter"
        "404":
          description: "No data"
        "409":
          description: "Partial content"
          schema:
            type: array
            items:
              $ref: '#/definitions/breakdown'
  /consumptions:
    get:
      tags:
      - Consumption
      summary: Retrieve consumptions
      operationId: getConsumptions
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/zoneId'
      responses:
        "200":
          description: "All data retreived"
          schema:
            type: array
            items:
              $ref: '#/definitions/consumption'
        "400":
          description: "Bad parameter"
        "404":
          description: "No data"
        "409":
          description: "Partial content"
          schema:
            type: array
            items:
              $ref: '#/definitions/consumption'
  /exchanges:
    get:
      tags:
      - Exchange
      summary: Retrieve exchanges
      operationId: getExchanges
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
        - $ref: '#/parameters/from'
        - $ref: '#/parameters/to'
        - $ref: '#/parameters/zoneId'
      responses:
        "200":
          description: "All data retreived"
          schema:
            type: array
            items:
              $ref: '#/definitions/exchange'
        "400":
          description: "Bad parameter"
        "404":
          description: "No data"
        "409":
          description: "Partial content"
          schema:
            type: array
            items:
              $ref: '#/definitions/exchange'
  /zones:
    get:
      tags:
      - Zone
      summary: Retrieve zones
      operationId: getZones
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "All data retreived"
          schema:
            type: array
            items:
              $ref: '#/definitions/zone'
  /zones/{id}:
    get:
      tags:
      - Zone
      summary: Retrieve zone
      operationId: getZone
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        required: true
        description: "The zone id"
        type: string
        pattern: "[A-Z]{2}(-[0-9]{1-2})?$"
      responses:
        "200":
          description: "All data retreived"
          schema:
            type: array
            items:
              $ref: '#/definitions/zone'
        "400":
          description: "Bad parameter"
        "404":
          description: "No data"
definitions:
  breakdown:
    type: object
    properties:
      timestamp:
        type: string
        format: date-time
      zoneId:
        type: string
        pattern: "[A-Z]{2}-[0-9]{1-2}$"
      breakdown:
        type: object
        properties:
          photovoltaic:
            $ref: '#/definitions/powerSource'
          windEnergy:
            $ref: '#/definitions/powerSource'
          hydraulic:
            $ref: '#/definitions/powerSource'
          nuclear:
            $ref: '#/definitions/powerSource'
          bioenergies:
            $ref: '#/definitions/powerSource'
          fossil:
            $ref: '#/definitions/powerSource'
  consumption:
    type: object
    properties:
      timestamp:
        type: string
        format: date-time
      zoneId:
        type: string
        pattern: "[A-Z]{2}-[0-9]{1-2}$"
      used:
        $ref: '#/definitions/powerConsumption'
      stepStorage:
        $ref: '#/definitions/powerConsumption'
  exchange:
    type: object
    properties:
      timestamp:
        type: string
        format: date-time
      sourceZone:
        type: string
        pattern: "[A-Z]{2}-[0-9]{1-2}$"
      targetZone:
        type: string
        pattern: "[A-Z]{2}-[0-9]{1-2}$"
      value:
        type: number
        format: int64
      unit:
        type: string
  powerConsumption:
    type: object
    properties:
      value:
        type: number
        format: int64
      unit:
        type: string
  powerSource:
    type: object
    properties:
      capacity:
        type: object
        properties:
          value:
            type: number
            format: int64
          unit:
            type: string
      production:
        type: object
        properties:
          value:
            type: number
            format: int64
          unit:
            type: string
      loadFactor:
        type: number
        format: double
  zone:
    type: object
    properties:
      id:
        type: string
        pattern: "[A-Z]{2}(-[0-9]{1-2})?$"
      name:
        type: string
      connections:
        type: array
        items:
          type: string
          pattern: "[A-Z]{2}(-[0-9]{1-2})?$"
parameters:
  from:
    in: "query"
    name: "from"
    description: "Start of the period"
    required: false
    type: "string"
    format: "date-time"
  to:
    in: "query"
    name: "to"
    description: "End of the period"
    required: false
    type: "string"
    format: "date-time"
  zoneId:
    in: "query"
    name: "zoneId"
    description: "Zone to retrieve data from"
    required: false
    type: string
    pattern: "[A-Z]{2}(-[0-9]{1-2})?$"
  valueFilter:
    in: "query"
    name: "value"
    description: "Filter on values"
    type: string
  loadFilter:
    in: "query"
    name: "load"
    description: "Filter on load factors"
    type: string
    pattern: "lowest|highest"
  powerSourceFilter:
    in: "query"
    name: "source"
    description: "Filter on sources"
    type: string
    pattern: "photovoltaic|windEnergy|hydaulic|nuclear|bioenergies|fossil"
  consumptionFilter:
    in: "query"
    name: "target"
    description: "Filter on consumptions"
    type: string
    pattern: "used|stepStorage"