steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/PETILLON-Sebastien/facteurs_charge.git']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
